name: Setup VNC Server with Cloudflare Tunnel

on:
  push:
    branches:
      - main

jobs:
  setup-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            xfce4 \
            xfce4-goodies \
            tightvncserver \
            curl \
            cloudflared \
            x11vnc \
            xvfb \
            sudo

      - name: Set root password
        run: |
          echo "root:admin@123" | sudo chpasswd
          echo "VNC password set to 'admin@123'"

      - name: Start VNC Server
        run: |
          export DISPLAY=:1
          export X11VNC_PASSWORD=admin@123
          export VNC_PORT=5901
          sudo Xvfb :1 -screen 0 1920x1080x24 &
          sleep 3
          sudo x11vnc -display :1 -passwd $X11VNC_PASSWORD -forever -shared &
          sleep 3
          sudo tightvncserver :1 -geometry 1920x1080 -depth 24
        background: true

      - name: Install Cloudflared
        run: |
          curl -LO https://github.com/cloudflare/cloudflared/releases/download/2022.11.3/cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Run Cloudflare Tunnel
        run: |
          cloudflared tunnel --url http://localhost:5901 &
          sleep 5
          tunnel_ip=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Cloudflare Tunnel IP:PORT: $tunnel_ip"

      - name: Keep Alive and Display Tunnel IP
        run: |
          echo "VNC Server and Cloudflare Tunnel are running."
          echo "Access VNC at: $tunnel_ip"
          echo "Tunnel IP:PORT is $tunnel_ip"
          while true; do sleep 3600; done
