name: VNC with TryCloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install XFCE and TigerVNC
        run: |
          echo "::group::Installing Dependencies"
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tigervnc-standalone-server tigervnc-common
          echo "::endgroup::"

      - name: Set Root Password
        run: |
          echo "::group::Setting Root Password"
          echo "root:admin@123" | sudo chpasswd
          echo "::endgroup::"

      - name: Configure VNC
        run: |
          echo "::group::Configuring VNC"
          mkdir -p ~/.vnc
          echo "admin@123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo -e "#!/bin/sh\nxrdb $HOME/.Xresources\nstartxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1 -geometry 1920x1080 -depth 24
          echo "::endgroup::"

      - name: Install Cloudflared
        run: |
          echo "::group::Installing Cloudflared"
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          echo "::endgroup::"

      - name: Start Cloudflared Tunnel
        run: |
          echo "::group::Starting Cloudflared Tunnel"
          cloudflared tunnel --url vnc://localhost:5901 &
          sleep 10 # Wait for tunnel to initialize
          TUNNEL_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "VNC Tunnel URL: $TUNNEL_URL"
          echo "::endgroup::"

      - name: Display Access Details
        run: |
          echo "::group::Access Details"
          echo "VNC URL: $TUNNEL_URL"
          echo "User: root"
          echo "Password: admin@123"
          echo "Resolution: 1920x1080"
          echo "Note: Access the VNC server using a VNC client with the above URL, user, and password."
          echo "::endgroup::"

      - name: Keep Alive
        run: |
          echo "::group::Keeping Workflow Alive"
          for i in {1..21600}; do # 6 hours = 21600 seconds
            echo "Keeping alive... ($i/21600)"
            sleep 1
          done
          echo "::endgroup::"
