name: Setup Server with XFCE, VNC, and TryCloudflare Tunneling

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  setup-server:
    runs-on: ubuntu-20.04
    timeout-minutes: 360  # 6 hours

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xfce4 tightvncserver wget curl git

    - name: Set Root Password
      run: |
        echo "root:admin@123" | sudo chpasswd

    - name: Configure VNC
      run: |
        echo "admin@123" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        tightvncserver :1 -geometry 1920x1080 -depth 24

    - name: Install TryCloudflare
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
        chmod +x /usr/local/bin/cloudflared

    - name: Start TryCloudflare Tunnel
      run: |
        nohup cloudflared tunnel --url localhost:5901 > /var/log/cloudflared.log 2>&1 &

    - name: Wait for Tunnel to Establish
      run: |
        sleep 10  # Wait for tunnel to start
        TUNNEL_URL=$(grep -o 'https://[^ ]*.trycloudflare.com' /var/log/cloudflared.log)
        echo "Tunnel URL: $TUNNEL_URL"
        echo "VNC User: root"
        echo "VNC Password: admin@123"
        echo "Access VNC via: $TUNNEL_URL"

    - name: Keep Alive
      run: |
        END_TIME=$(( $(date +%s) + 21600 ))  # 6 hours in seconds
        while [ $(date +%s) -lt $END_TIME ]; do
          sleep 60
        done
