name: RDPX Ubuntu

on:
  workflow_dispatch:

jobs:
  ubuntu-gui:
    runs-on: ubuntu-latest
    timeout-minutes: 540  # 9 jam
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY }} --hostname ubuntu-gui --ssh

    - name: Install Desktop, VNC, Firefox
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies tightvncserver

    - name: Set Root Password
      run: |
        echo "root:admin123" | sudo chpasswd

    - name: Set VNC Password
      run: |
        mkdir -p ~/.vnc
        echo "admin123" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start VNC Server
      run: |
        vncserver :1 -geometry 1920x1080 -depth 24

    - name: Keep Runner Alive
      run: sleep 21600
